
export default function BESSSection() {
  return (
    <section className="bg-white py-16 px-6 md:px-16">
      <div className="max-w-7xl mx-auto">

        {/* Heading */}
        <div className="mb-10 text-center">
          <h4 className="text-sm text-[#FC763A] font-semibold tracking-wide mb-2">
            WHAT IS BESS
          </h4>

          <h2 className="text-3xl md:text-4xl font-bold text-[#686868] mb-4">
            Intelligent Energy. Stored & Ready.
          </h2>

        </div>

        {/* Content Grid */}
        <div className="grid md:grid-cols-2 gap-10 items-start">

          {/* Left Content */}
          <div className="space-y-6 text-gray-700 text-lg leading-relaxed">
            <p>
              A Battery Energy Storage System (BESS) is a technology that captures
              surplus electricity generated by your rooftop solar panels and stores
              it in high-capacity battery banks for use when solar generation is low
              — during evenings, cloudy days, or grid outages.
            </p>

            <p>
              Unlike a conventional solar system that feeds excess energy back to
              the grid (often at low rates), a BESS-integrated system lets you store
              that energy and consume it yourself — maximising your return on
              investment and giving you true energy independence.
            </p>

            <p>
              At TrueSun, we design, supply, and commission BESS solutions tailored
              to your energy consumption profile, load requirements, and site
              conditions — ensuring you get the right battery capacity and the right
              technology for your needs.
            </p>
          </div>

          {/* Right Side - Image + Key Points */}
          <div>
            <div className="rounded-xl overflow-hidden border">
              <img
                src="https://img.freepik.com/premium-photo/industrial-battery-storage-system-renewable-energy_1283272-1888.jpg?semt=ais_incoming&w=740&q=80"
                alt="BESS System"
                className="w-full h-50 object-cover"
              />
            </div>

            {/* Key Points */}
            <div className="mt-6 space-y-4">
              <div className="flex items-start gap-3">
                <span className="text-yellow-500 text-xl">✔</span>
                <p className="text-gray-700">
                  Store excess solar energy efficiently
                </p>
              </div>

              <div className="flex items-start gap-3">
                <span className="text-yellow-500 text-xl">✔</span>
                <p className="text-gray-700">
                  Use power anytime – day or night
                </p>
              </div>

              <div className="flex items-start gap-3">
                <span className="text-yellow-500 text-xl">✔</span>
                <p className="text-gray-700">
                  Reduce grid dependency & increase savings
                </p>
              </div>

              <div className="flex items-start gap-3">
                <span className="text-yellow-500 text-xl">✔</span>
                <p className="text-gray-700">
                  Reliable backup during outages
                </p>
              </div>
            </div>
          </div>

        </div>


      </div>
    </section>
  );
}