import { Leaf, Factory, Zap, Globe, ArrowRight, CheckCircle2 } from 'lucide-react';
import { useState } from 'react';
import LeadPopup from '../../../LeadPopup';

const CarbonFootprintSectionWhite = () => {
    const scopes = [
        {
            id: "01",
            title: "Scope 1",
            label: "Direct Emissions",
            desc: "Fuel combustion & company vehicles.",
            icon: <Factory className="w-6 h-6" />,
        },
        {
            id: "02",
            title: "Scope 2",
            label: "Energy Indirect",
            desc: "Purchased electricity & heating.",
            icon: <Zap className="w-6 h-6" />,
        },
        {
            id: "03",
            title: "Scope 3",
            label: "Value Chain Indirect",
            desc: "Suppliers, travel & product waste.",
            icon: <Globe className="w-6 h-6" />,
        },
    ];
    const [openLeadPopup, setOpenLeadPopup] = useState(false);

    return (
        <section className="bg-white text-slate-800 py-14 px-6 overflow-hidden">
            <div className="max-w-7xl mx-auto">

                {/* Top Header Section */}
                <div className="max-w-5xl mx-auto text-center mb-20">
                    <div>
                        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#FC763A]/10 border border-[#FC763A]/20 text-[#FC763A] text-sm font-semibold mb-6">
                            <Leaf size={16} />
                            Sustainability Framework
                        </div>
                        <h2 className="text-3xl md:text-5xl font-extrabold text-[#686868] leading-tight tracking-tight">
                            What is <span className="text-[#FC763A]">Carbon Footprinting?</span>
                        </h2>
                    </div>
                    <div className="">
                        <p className="text-slate-600 text-lg leading-relaxed">
                            We measure the total greenhouse gas emissions generated by your organization using the
                            <span className="text-slate-950 font-semibold"> Greenhouse Gas Protocol</span>.
                            Our framework ensures your accounting is structured, audit-ready, and fully ESG-compliant.
                        </p>
                    </div>
                </div>

                {/* The Scope Bento Grid */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-20">
                    {scopes.map((item) => (
                        <div key={item.id} className="group relative p-8 rounded-3xl bg-slate-50 border border-slate-100 hover:border-[#FC763A]/60 hover:bg-slate-100/50 transition-all duration-300 shadow-xl hover:shadow-2xl">
                            <div className="relative z-10">
                                <div className="flex justify-between items-start mb-10">
                                    <div className="p-3.5 rounded-2xl bg-white text-[#FC763A] border border-slate-100 shadow-inner">
                                        {item.icon}
                                    </div>
                                    <span className="text-slate-600 font-mono text-5xl font-bold">{item.id}</span>
                                </div>

                                <p className="text-[#FC763A] text-xs font-bold uppercase tracking-widest mb-2">{item.label}</p>
                                <h3 className="text-2xl font-bold text-slate-950 mb-3">{item.title}</h3>
                                <p className="text-slate-600 leading-relaxed text-sm">{item.desc}</p>
                            </div>
                        </div>
                    ))}
                </div>

                {/* Benefits Section */}
                <div className="grid lg:grid-cols-5 gap-8 items-center  ">

                    {/* Main Assessment CTA/Header */}
                    <div className="lg:col-span-2">
                        <h3 className="text-3xl font-extrabold text-[#686868] leading-tight mb-6 tracking-tight">
                            Why perform an assessment?
                        </h3>
                        <p className="font-medium text-slate-700 text-lg mb-10">
                            Take the first step toward a net-zero future with data-driven insights.
                        </p>
                        <button

                            onClick={() => setOpenLeadPopup(true)}
                            className="inline-flex items-center gap-2.5 px-6 py-3.5 rounded-xl bg-[#FC763A] text-white font-semibold group hover:bg-[#e5652e] transition-colors shadow-lg shadow-[#FC763A]/20">
                            Get Started <ArrowRight className="group-hover:translate-x-1 transition-transform" size={18} />
                        </button>
                    </div>

                    {/* Feature List Grid */}
                    <div className="lg:col-span-3 grid sm:grid-cols-2 gap-6">
                        {[
                            "Identify key emission sources",
                            "Build a clear decarbonization roadmap",
                            "Align with ESG disclosures",
                            "Prepare for evolving climate regulations"
                        ].map((benefit, idx) => (
                            <div key={idx} className="bg-white border border-slate-100 p-6 rounded-2xl flex gap-4 items-center shadow-sm hover:shadow transition-shadow">
                                <CheckCircle2 className="text-[#FC763A] shrink-0" size={24} strokeWidth={2.5} />
                                <span className="text-slate-800 font-semibold leading-snug">{benefit}</span>
                            </div>
                        ))}
                    </div>

                </div>
                <div className=' max-w-7xl mt-15 mx-auto text-center'>
                    <h1 className='text-4xl py-5  font-bold'>From Measurement to Action</h1>
                    <p className='text-md '>At TrueSun, we go beyond reporting. We help you reduce and offset emissions through renewable energy solutions, I-RECs, and carbon credits.</p>
                </div>
                {openLeadPopup && (
                    <LeadPopup onClose={() => setOpenLeadPopup(false)} />
                )}
            </div>
        </section>
    );
};

export default CarbonFootprintSectionWhite;