 

import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

const DEFAULT_ITEMS = [
  {
    id: "cost",
    question: "I don’t have any available roof space available but ground space is available. Can I utilize this for solar power generation?",
    answer:
      "Yes. The regulation allows you to use this space for solar power generation.",
  },
  {
    id: "timeline",
    question: "What is the minimum area required to install a rooftop Solar Plant?",
    answer:
      "100 Sq feet or 10 meter square to install 1KWp Solar plant.",
  },
  {
    id: "maintenance",
    question: "How much energy can a 1KWp solar plant generate?",
    answer:
      "A 1KWp solar plant will generate approximately 120 units per month. However, the exact power generated will be subject to location of the plant.",
  },
  {
    id: "battery",
    question: "Will my rooftop will get damaged while installing a rooftop solar plant?",
    answer:
      "Not at all! Robust Design is the core of our offerings. We install the solar plant on flat cement and metal roofs without puncturing the roof.  Load bearing capacity and wind speed zone are in our primary considerations while designing & installing the plant.",
  },
   {
    id: "required",
    question: "What is the maintenance required for a solar plant?",
    answer:
      "Once installed, the plant is almost maintenance free.  All that is required from you is to clean the dust on the panels once or twice in a month.Preventive health check twice a year would ascertain plant longetivity.",
  },
    {
    id: "required",
    question: "What are the warranties on the system?",
    answer:
      "30 year performance warranty for panel and 5 year on inverter are offered by the manufacturer.",
  },
  {
    id: "required7",
    question: "What is solar rooftop?",
    answer:
      "Solar rooftop are solar panels placed on top of roofs of commercial, institutional or residential buildings. They capture sunlight and produce electricity to power your appliances and machineries.",
  },
  {
    id: "required",
    question: "Why is rooftop solar a good investment?",
    answer:
      "When you install Solar plant in your building, it generates power which is much cheaper than the one you are buying from utility. Life of the plant is 25 years. There is upfront cost which gets covered in 3-4 years and then you have free electricity for remaining years. This way you save a lot of money and like many other investment that might give you 10-15%, solar plant can promise as high as 40% return.",
  },
  {
    id: "required",
    question: "How to apply for a solar rooftop installation?",
    answer:
      "It is a simple process you have to share your electricity bill with a service provider like us. Post which we undertake a feasibility check, site visit to evaluate roof area etc and share the quotation.",
  },
  {
    id: "required",
    question: "What is the process for installing your solar panels for offices?",
    answer:
      "It’s simple process you have to share your electricity bill with a service provider like us. Post which we undertake a feasibility check, site visit and share the quotation.",
  },
  {
    id: "required",
    question: "Why should we go for a professional company to install solar panels?",
    answer:
      "A professional team can make the difference between an efficient, high-yield system from the one that doesn’t work as it should. DIY solar can become a pretty confusing job and may lead to poor generation. The work involves civil and electrical work so its best done by a professional agency.",
  },
  {
    id: "required",
    question: "What is a Net Meter?",
    answer:
      "A Net Meter records the net energy consumed after considering the ‘import/ export – from/to’ your electricity distribution company. This meter records the incoming units from the grid and the ones exported from the solar plant, booking only those consumed by you in the difference.  Hence, a Net Meter keeps a track on units consumed and records them for bill calculations.",
  },
  {
    id: "required",
    question: "What happens if my Export is more than Import?",
    answer:
      "Your excess Energy generated during the month will remain intact. The surplus units will be shown as Credit with your host electric distribution company. This will get adjusted in your subsequent monthly power bills.",
  },
  {
    id: "required",
    question: "Will be paid for Excess Units Generated by my solar plant?",
    answer:
      "Yes! Most of the Utilities (Electric Distribution Companies) follow an April to March Calendar for surplus Energy settlement with the customer. Any surplus Energy of the customer with the  Utility in March will be settled at the pre-determined rate in subsequent months’ bills.",
  },
  {
    id: "required",
    question: "What capacity of Solar Plant can I install in order to avail Net Meter benefits?",
    answer:
      "It depends upon the policies of the state you are connected in. For instance, in Maharashtra State, you can install the Solar Plant under Net Metering to the extent of your connected load or contract demand but not more than 1000KWp or 1 MW.",
  },
  {
    id: "16",
    question: "Will my equipments run comfortably on solar power?",
    answer:
      "Yes! With Net Metering in place, you will keep enjoying the service as it was earlier. When the sunlight is out, you are getting power from the utilities, so all your devices including AC, fridge and microwaves run as usual.",
  },
  {
    id: "required",
    question: "What kind of financing is available for my project?",
    answer:
      "The financing options are through debt at attractive rates, subsidies through MEDA and SECI and investors for large size projects under Build-Own-Operate-Transfer (BOOT) model. ",
  },
  {
    id: "required",
    question: "Does Truesun help in loans sanctioning process?",
    answer:
      "Yes we do. All we need from you is the complete list of documents required for applying for loan and we will do the rest.",
  },
  {
    id: "required",
    question: "Who is eligible for subsidy?",
    answer:
      "All type of residential buildings, schools, health institutions including medical college & hospitals, universities, educational institutions under trusts, Community centers, welfare homes, old age homes and orphanages.",
  },
  {
    id: "required",
    question: "Who is not eligible for subsidy?",
    answer:
      "No subsidy is applicable for industrial and commercial establishments. Additionally all types of government buildings, institutions and Organizations including PSUs are not eligible to apply for subsidy.",
  },
  {
    id: "required",
    question: "Can we help you get subsidies?",
    answer:
      "Yes! If you are under the eligible category, Truesun can apply for the same and get necessary approvals. The final disbursement, however, is governed by the authorized agency.",
  },
  {
    id: "required",
    question: "Can cooperative societies get a loan?",
    answer:
      "Yes. This is usually processed from the bank where the society is holding an account, keeping current Fixed Deposits as collateral.",
  },
  {
    id: "required",
    question: "How to calculate the area and cost for a rooftop solar installation?",
    answer:
      "As a thumb rule, 1 KW solar plant requires 80-100 sq feet area and 1 KW cost 60,000 and 100 KW cost approx.. 40 lakhs.",
  },
  {
    id: "required",
    question: "Is installing a solar panel installation really expensive?",
    answer:
      "With the given advancement in technology and reducing cost of panels and other equipment’s, solar plant upfront cost has reduced. Further the life of plant is more than 25 years and payback is less than 3 years. Also there are many financing mechanisms available to reduce the upfront cost.",
  },

];



const INITIAL_VISIBLE = 5;

export default function PremiumFAQ({ items = DEFAULT_ITEMS }) {
  const [openItem, setOpenItem] = useState<string | null>(null);
  const [showAll, setShowAll] = useState(false);

  const visibleItems = showAll ? items : items.slice(0, INITIAL_VISIBLE);

  return (
    <section className="mx-auto max-w-4xl overflow-hidden px-4 py-16">
      
      {/* Header */}
      <motion.header
        initial={{ opacity: 0, y: -20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        className="mb-12 text-center"
      >
        <h2 className="text-4xl font-black tracking-tight text-[#686868]">
          Frequently Asked <span className="text-[#FC763A]">Questions</span>
        </h2>
        <p className="mt-4 text-lg text-gray-500">
          Everything you need to know about switching to clean energy.
        </p>
      </motion.header>

      {/* FAQ List */}
      <div className="space-y-6">
        {visibleItems.map(({ id, question, answer }, index) => {
          const isOpen = openItem === id;
          const slideFrom = index % 2 === 0 ? 80 : -80;

          return (
            <motion.div
              key={id}
              initial={{ opacity: 0, x: slideFrom }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true, margin: "-50px" }}
              transition={{
                duration: 0.6,
                delay: 0.1,
                type: "spring",
                stiffness: 100,
              }}
              className={`group overflow-hidden rounded-2xl border transition-shadow duration-300 ${
                isOpen
                  ? "border-[#FC763A] bg-orange-50/30 shadow-lg"
                  : "border-gray-200 bg-white hover:border-orange-300 hover:shadow-md"
              }`}
            >
              <button
                onClick={() => setOpenItem(isOpen ? null : id)}
                className="flex w-full items-center justify-between p-6 text-left"
              >
                <span
                  className={`text-lg font-bold transition-colors ${
                    isOpen ? "text-[#FC763A]" : "text-gray-900"
                  }`}
                >
                  {question}
                </span>

                <div
                  className={`ml-4 shrink-0 rounded-full p-1 transition-colors ${
                    isOpen
                      ? "bg-[#FC763A] text-white"
                      : "bg-gray-100 text-gray-500"
                  }`}
                >
                  <ChevronDown
                    className={`h-5 w-5 transition-transform duration-500 ${
                      isOpen ? "rotate-180" : ""
                    }`}
                  />
                </div>
              </button>

              <AnimatePresence>
                {isOpen && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{
                      duration: 0.4,
                      ease: [0.04, 0.62, 0.23, 0.98],
                    }}
                  >
                    <div className="px-6 pb-6">
                      <div className="mb-4 h-px w-full bg-orange-100" />
                      <p className="text-gray-600 leading-relaxed italic">
                        {answer}
                      </p>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          );
        })}
      </div>

      {/* Show More Button */}
      {items.length > INITIAL_VISIBLE && (
        <div className="mt-10 text-center">
          <button
            onClick={() => setShowAll(!showAll)}
            className="rounded-full bg-[#FC763A] px-8 py-3 text-white font-semibold shadow-lg  transition"
          >
            {showAll ? "Show Less" : "Show More FAQs"}
          </button>
        </div>
      )}
    </section>
  );
}